<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FZ8VX6BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fZ8VX6B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fZ8VX6B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'application' => ['privates', '.errored..service_locator.fZ8VX6B.App\\Entity\\Application', NULL, 'Cannot autowire service ".service_locator.fZ8VX6B": it needs an instance of "App\\Entity\\Application" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'application' => 'App\\Entity\\Application',
        ]);
    }
}
