<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BZhIT9NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bZhIT9N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bZhIT9N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cv.storage' => ['privates', 'cv.storage', 'getCv_StorageService', true],
        ], [
            'cv.storage' => 'League\\Flysystem\\Filesystem',
        ]);
    }
}
