<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationControllerapplyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4YFDerM.App\Controller\ApplicationController::apply()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4YFDerM.App\\Controller\\ApplicationController::apply()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dto' => ['privates', 'App\\Dto\\Application\\CreateApplicationDto', NULL, 'Cannot autowire service "App\\Dto\\Application\\CreateApplicationDto": argument "$jobOfferId" of method "__construct()" is type-hinted "int", you should configure its value explicitly.'],
        ], [
            'dto' => 'App\\Dto\\Application\\CreateApplicationDto',
        ]))->withContext('App\\Controller\\ApplicationController::apply()', $container);
    }
}
