<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationControllercandidateProfileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fZ8VX6B.App\Controller\ApplicationController::candidateProfile()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fZ8VX6B.App\\Controller\\ApplicationController::candidateProfile()'] = ($container->privates['.service_locator.fZ8VX6B'] ?? $container->load('get_ServiceLocator_FZ8VX6BService'))->withContext('App\\Controller\\ApplicationController::candidateProfile()', $container);
    }
}
