<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApplicationController' shared autowired service.
     *
     * @return \App\Controller\ApplicationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ApplicationController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ApplicationService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PaginatorService.php';

        $a = ($container->privates['App\\Repository\\ApplicationRepository'] ?? $container->load('getApplicationRepositoryService'));

        $container->services['App\\Controller\\ApplicationController'] = $instance = new \App\Controller\ApplicationController(new \App\Service\ApplicationService($a, ($container->privates['App\\Repository\\CandidateRepository'] ?? $container->load('getCandidateRepositoryService')), ($container->privates['App\\Repository\\JobOfferRepository'] ?? $container->load('getJobOfferRepositoryService')), ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService'))), $a, ($container->privates['App\\Service\\PaginatorService'] ??= new \App\Service\PaginatorService()));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ApplicationController', $container));

        return $instance;
    }
}
