<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationControlleroverrideService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jcnI7hi.App\Controller\ApplicationController::override()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jcnI7hi.App\\Controller\\ApplicationController::override()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'application' => ['privates', '.errored..service_locator.jcnI7hi.App\\Entity\\Application', NULL, 'Cannot autowire service ".service_locator.jcnI7hi": it needs an instance of "App\\Entity\\Application" but this type has been excluded because it\'s a Doctrine entity.'],
            'dto' => ['privates', 'App\\Dto\\Application\\OverrideMatchDto', NULL, 'Cannot autowire service "App\\Dto\\Application\\OverrideMatchDto": argument "$matchLevel" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'application' => 'App\\Entity\\Application',
            'dto' => 'App\\Dto\\Application\\OverrideMatchDto',
        ]))->withContext('App\\Controller\\ApplicationController::override()', $container);
    }
}
