<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidateControllerdownloadCvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XtTlLCx.App\Controller\CandidateController::downloadCv()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XtTlLCx.App\\Controller\\CandidateController::downloadCv()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'candidate' => ['privates', '.errored..service_locator.XtTlLCx.App\\Entity\\Candidate', NULL, 'Cannot autowire service ".service_locator.XtTlLCx": it needs an instance of "App\\Entity\\Candidate" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'candidate' => 'App\\Entity\\Candidate',
        ]))->withContext('App\\Controller\\CandidateController::downloadCv()', $container);
    }
}
