<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateApplicationDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\Application\CreateApplicationDto' shared autowired service.
     *
     * @return \App\Dto\Application\CreateApplicationDto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Dto\\Application\\CreateApplicationDto": argument "$jobOfferId" of method "__construct()" is type-hinted "int", you should configure its value explicitly.');
    }
}
