<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidateControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zK4PFZG.App\Controller\CandidateController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zK4PFZG.App\\Controller\\CandidateController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dto' => ['privates', 'App\\Dto\\Candidate\\CreateCandidateDto', NULL, 'Cannot autowire service "App\\Dto\\Candidate\\CreateCandidateDto": argument "$fullName" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'dto' => 'App\\Dto\\Candidate\\CreateCandidateDto',
        ]))->withContext('App\\Controller\\CandidateController::create()', $container);
    }
}
