<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidateControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JDB04sS.App\Controller\CandidateController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JDB04sS.App\\Controller\\CandidateController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dto' => ['privates', 'App\\Dto\\Candidate\\UpdateCandidateDto', 'getUpdateCandidateDtoService', true],
        ], [
            'dto' => 'App\\Dto\\Candidate\\UpdateCandidateDto',
        ]))->withContext('App\\Controller\\CandidateController::update()', $container);
    }
}
