<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateCandidateDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\Candidate\CreateCandidateDto' shared autowired service.
     *
     * @return \App\Dto\Candidate\CreateCandidateDto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Dto\\Candidate\\CreateCandidateDto": argument "$fullName" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
