<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobOfferControllerdeleteJobOfferService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sGYOeyd.App\Controller\JobOfferController::deleteJobOffer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sGYOeyd.App\\Controller\\JobOfferController::deleteJobOffer()'] = ($container->privates['.service_locator.sGYOeyd'] ?? $container->load('get_ServiceLocator_SGYOeydService'))->withContext('App\\Controller\\JobOfferController::deleteJobOffer()', $container);
    }
}
