<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobOfferControllerupdateJobOfferService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RpfXO8W.App\Controller\JobOfferController::updateJobOffer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RpfXO8W.App\\Controller\\JobOfferController::updateJobOffer()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jobOffer' => ['privates', '.errored..service_locator.RpfXO8W.App\\Entity\\JobOffer', NULL, 'Cannot autowire service ".service_locator.RpfXO8W": it needs an instance of "App\\Entity\\JobOffer" but this type has been excluded because it\'s a Doctrine entity.'],
            'dto' => ['privates', 'App\\Dto\\JobOffer\\UpdateJobOfferDto', 'getUpdateJobOfferDtoService', true],
        ], [
            'jobOffer' => 'App\\Entity\\JobOffer',
            'dto' => 'App\\Dto\\JobOffer\\UpdateJobOfferDto',
        ]))->withContext('App\\Controller\\JobOfferController::updateJobOffer()', $container);
    }
}
