<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPullCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.League\FlysystemBundle\Command\PullCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.League\\FlysystemBundle\\Command\\PullCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('flysystem:pull', [], 'Pull a file from a configured Flysystem storage to the local filesystem.', false, #[\Closure(name: 'League\\FlysystemBundle\\Command\\PullCommand')] fn (): \League\FlysystemBundle\Command\PullCommand => ($container->privates['League\\FlysystemBundle\\Command\\PullCommand'] ?? $container->load('getPullCommandService')));
    }
}
