<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecruiterControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RecruiterController' shared autowired service.
     *
     * @return \App\Controller\RecruiterController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'RecruiterController.php';

        $container->services['App\\Controller\\RecruiterController'] = $instance = new \App\Controller\RecruiterController(($container->privates['App\\Repository\\JobOfferRepository'] ?? $container->load('getJobOfferRepositoryService')), ($container->privates['App\\Repository\\ApplicationRepository'] ?? $container->load('getApplicationRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\RecruiterController', $container));

        return $instance;
    }
}
