<?php

namespace ContainerHqhz7Dg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateCandidateDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\Candidate\UpdateCandidateDto' shared autowired service.
     *
     * @return \App\Dto\Candidate\UpdateCandidateDto
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Dto'.\DIRECTORY_SEPARATOR.'Candidate'.\DIRECTORY_SEPARATOR.'UpdateCandidateDto.php';

        return $container->privates['App\\Dto\\Candidate\\UpdateCandidateDto'] = new \App\Dto\Candidate\UpdateCandidateDto();
    }
}
