<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260510203413 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT DEFAULT NULL, match_level VARCHAR(10) DEFAULT NULL, score_summary TEXT DEFAULT NULL, recruiter_note TEXT DEFAULT NULL, recruiter_match_override VARCHAR(10) DEFAULT NULL, status VARCHAR(11) NOT NULL, applied_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, candidate_id INT NOT NULL, job_offer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A45BDDC191BD8781 ON application (candidate_id)');
        $this->addSql('CREATE INDEX IDX_A45BDDC13481D195 ON application (job_offer_id)');
        $this->addSql('CREATE TABLE candidate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, phone VARCHAR(20) DEFAULT NULL, cv_file_path VARCHAR(255) DEFAULT NULL, skills JSON DEFAULT NULL, experience_months INT DEFAULT NULL, languages JSON DEFAULT NULL, summary TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, candidate_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C8B28E4428BF7E34 ON candidate (candidate_user_id)');
        $this->addSql('CREATE TABLE job_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, requirements JSON NOT NULL, experience_min INT NOT NULL, location VARCHAR(255) DEFAULT NULL, work_mode VARCHAR(10) NOT NULL, status VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_288A3A4E7E3C61F9 ON job_offer (owner_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC191BD8781 FOREIGN KEY (candidate_id) REFERENCES candidate (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC13481D195 FOREIGN KEY (job_offer_id) REFERENCES job_offer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate ADD CONSTRAINT FK_C8B28E4428BF7E34 FOREIGN KEY (candidate_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC191BD8781');
        $this->addSql('ALTER TABLE application DROP CONSTRAINT FK_A45BDDC13481D195');
        $this->addSql('ALTER TABLE candidate DROP CONSTRAINT FK_C8B28E4428BF7E34');
        $this->addSql('ALTER TABLE job_offer DROP CONSTRAINT FK_288A3A4E7E3C61F9');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE candidate');
        $this->addSql('DROP TABLE job_offer');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
