<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_58Bgo_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5_8Bgo.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5_8Bgo.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApplicationController::apply' => ['privates', '.service_locator.4YFDerM.App\\Controller\\ApplicationController::apply()', 'getApplicationControllerapplyService', true],
            'App\\Controller\\ApplicationController::jobOfferApplications' => ['privates', '.service_locator.sGYOeyd.App\\Controller\\ApplicationController::jobOfferApplications()', 'getApplicationControllerjobOfferApplicationsService', true],
            'App\\Controller\\ApplicationController::candidateProfile' => ['privates', '.service_locator.fZ8VX6B.App\\Controller\\ApplicationController::candidateProfile()', 'getApplicationControllercandidateProfileService', true],
            'App\\Controller\\ApplicationController::override' => ['privates', '.service_locator.jcnI7hi.App\\Controller\\ApplicationController::override()', 'getApplicationControlleroverrideService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator._hmN2Gu.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\CandidateController::create' => ['privates', '.service_locator.zK4PFZG.App\\Controller\\CandidateController::create()', 'getCandidateControllercreateService', true],
            'App\\Controller\\CandidateController::update' => ['privates', '.service_locator.JDB04sS.App\\Controller\\CandidateController::update()', 'getCandidateControllerupdateService', true],
            'App\\Controller\\JobOfferController::getJobOffer' => ['privates', '.service_locator.sGYOeyd.App\\Controller\\JobOfferController::getJobOffer()', 'getJobOfferControllergetJobOfferService', true],
            'App\\Controller\\JobOfferController::createJobOffer' => ['privates', '.service_locator.t9otC_a.App\\Controller\\JobOfferController::createJobOffer()', 'getJobOfferControllercreateJobOfferService', true],
            'App\\Controller\\JobOfferController::updateJobOffer' => ['privates', '.service_locator.RpfXO8W.App\\Controller\\JobOfferController::updateJobOffer()', 'getJobOfferControllerupdateJobOfferService', true],
            'App\\Controller\\JobOfferController::deleteJobOffer' => ['privates', '.service_locator.sGYOeyd.App\\Controller\\JobOfferController::deleteJobOffer()', 'getJobOfferControllerdeleteJobOfferService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApplicationController:apply' => ['privates', '.service_locator.4YFDerM.App\\Controller\\ApplicationController::apply()', 'getApplicationControllerapplyService', true],
            'App\\Controller\\ApplicationController:jobOfferApplications' => ['privates', '.service_locator.sGYOeyd.App\\Controller\\ApplicationController::jobOfferApplications()', 'getApplicationControllerjobOfferApplicationsService', true],
            'App\\Controller\\ApplicationController:candidateProfile' => ['privates', '.service_locator.fZ8VX6B.App\\Controller\\ApplicationController::candidateProfile()', 'getApplicationControllercandidateProfileService', true],
            'App\\Controller\\ApplicationController:override' => ['privates', '.service_locator.jcnI7hi.App\\Controller\\ApplicationController::override()', 'getApplicationControlleroverrideService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator._hmN2Gu.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\CandidateController:create' => ['privates', '.service_locator.zK4PFZG.App\\Controller\\CandidateController::create()', 'getCandidateControllercreateService', true],
            'App\\Controller\\CandidateController:update' => ['privates', '.service_locator.JDB04sS.App\\Controller\\CandidateController::update()', 'getCandidateControllerupdateService', true],
            'App\\Controller\\JobOfferController:getJobOffer' => ['privates', '.service_locator.sGYOeyd.App\\Controller\\JobOfferController::getJobOffer()', 'getJobOfferControllergetJobOfferService', true],
            'App\\Controller\\JobOfferController:createJobOffer' => ['privates', '.service_locator.t9otC_a.App\\Controller\\JobOfferController::createJobOffer()', 'getJobOfferControllercreateJobOfferService', true],
            'App\\Controller\\JobOfferController:updateJobOffer' => ['privates', '.service_locator.RpfXO8W.App\\Controller\\JobOfferController::updateJobOffer()', 'getJobOfferControllerupdateJobOfferService', true],
            'App\\Controller\\JobOfferController:deleteJobOffer' => ['privates', '.service_locator.sGYOeyd.App\\Controller\\JobOfferController::deleteJobOffer()', 'getJobOfferControllerdeleteJobOfferService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApplicationController::apply' => '?',
            'App\\Controller\\ApplicationController::jobOfferApplications' => '?',
            'App\\Controller\\ApplicationController::candidateProfile' => '?',
            'App\\Controller\\ApplicationController::override' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\CandidateController::create' => '?',
            'App\\Controller\\CandidateController::update' => '?',
            'App\\Controller\\JobOfferController::getJobOffer' => '?',
            'App\\Controller\\JobOfferController::createJobOffer' => '?',
            'App\\Controller\\JobOfferController::updateJobOffer' => '?',
            'App\\Controller\\JobOfferController::deleteJobOffer' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApplicationController:apply' => '?',
            'App\\Controller\\ApplicationController:jobOfferApplications' => '?',
            'App\\Controller\\ApplicationController:candidateProfile' => '?',
            'App\\Controller\\ApplicationController:override' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\CandidateController:create' => '?',
            'App\\Controller\\CandidateController:update' => '?',
            'App\\Controller\\JobOfferController:getJobOffer' => '?',
            'App\\Controller\\JobOfferController:createJobOffer' => '?',
            'App\\Controller\\JobOfferController:updateJobOffer' => '?',
            'App\\Controller\\JobOfferController:deleteJobOffer' => '?',
        ]);
    }
}
