<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_V1z6IGGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.V1z6IGG' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'messenger'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'MessageHandler'.\DIRECTORY_SEPARATOR.'ScoreCandidateHandler.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'LLM'.\DIRECTORY_SEPARATOR.'CandidateScorer.php';

        $a = ($container->privates['App\\Repository\\ApplicationRepository'] ?? $container->load('getApplicationRepositoryService'));

        if (isset($container->privates['.messenger.handler_descriptor.V1z6IGG'])) {
            return $container->privates['.messenger.handler_descriptor.V1z6IGG'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\ScoreCandidateHandler($a, new \App\Service\LLM\CandidateScorer(($container->privates['App\\Service\\LLM\\ClaudeClient'] ?? $container->load('getClaudeClientService')))), []);

        if (isset($container->privates['.messenger.handler_descriptor.V1z6IGG'])) {
            return $container->privates['.messenger.handler_descriptor.V1z6IGG'];
        }

        return $container->privates['.messenger.handler_descriptor.V1z6IGG'] = $instance;
    }
}
