<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SGYOeydService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sGYOeyd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sGYOeyd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jobOffer' => ['privates', '.errored..service_locator.sGYOeyd.App\\Entity\\JobOffer', NULL, 'Cannot autowire service ".service_locator.sGYOeyd": it needs an instance of "App\\Entity\\JobOffer" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'jobOffer' => 'App\\Entity\\JobOffer',
        ]);
    }
}
