<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._hmN2Gu.App\Controller\AuthController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._hmN2Gu.App\\Controller\\AuthController::register()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dto' => ['privates', 'App\\Dto\\Auth\\RegisterUserDto', NULL, 'Cannot autowire service "App\\Dto\\Auth\\RegisterUserDto": argument "$email" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
            'userService' => ['privates', 'App\\Service\\UserService', 'getUserServiceService', true],
            'jwtManager' => ['services', 'lexik_jwt_authentication.jwt_manager', 'getLexikJwtAuthentication_JwtManagerService', true],
        ], [
            'dto' => 'App\\Dto\\Auth\\RegisterUserDto',
            'userService' => 'App\\Service\\UserService',
            'jwtManager' => '?',
        ]))->withContext('App\\Controller\\AuthController::register()', $container);
    }
}
