<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationControllerjobOfferApplicationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sGYOeyd.App\Controller\ApplicationController::jobOfferApplications()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sGYOeyd.App\\Controller\\ApplicationController::jobOfferApplications()'] = ($container->privates['.service_locator.sGYOeyd'] ?? $container->load('get_ServiceLocator_SGYOeydService'))->withContext('App\\Controller\\ApplicationController::jobOfferApplications()', $container);
    }
}
