<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidateControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CandidateController' shared autowired service.
     *
     * @return \App\Controller\CandidateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CandidateController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CandidateService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CvUploadService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'LLM'.\DIRECTORY_SEPARATOR.'CvParser.php';

        $a = ($container->privates['cv.storage'] ?? $container->load('getCv_StorageService'));

        $container->services['App\\Controller\\CandidateController'] = $instance = new \App\Controller\CandidateController(new \App\Service\CandidateService(($container->privates['App\\Repository\\CandidateRepository'] ?? $container->load('getCandidateRepositoryService')), new \App\Service\CvUploadService($a), new \App\Service\LLM\CvParser(($container->privates['App\\Service\\LLM\\ClaudeClient'] ?? $container->load('getClaudeClientService')), $a), ($container->privates['App\\Service\\Elasticsearch\\CandidateIndexer'] ?? $container->load('getCandidateIndexerService'))));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\CandidateController', $container));

        return $instance;
    }
}
