<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidateIndexerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Elasticsearch\CandidateIndexer' shared autowired service.
     *
     * @return \App\Service\Elasticsearch\CandidateIndexer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Elasticsearch'.\DIRECTORY_SEPARATOR.'CandidateIndexer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'ClientEndpointsTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'EndpointTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'NamespaceTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'elasticsearch'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Client.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'ElasticsearchClientFactory.php';

        return $container->privates['App\\Service\\Elasticsearch\\CandidateIndexer'] = new \App\Service\Elasticsearch\CandidateIndexer(\App\Factory\ElasticsearchClientFactory::create($container->getEnv('ELASTICSEARCH_URL')));
    }
}
