<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClaudeClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\LLM\ClaudeClient' shared autowired service.
     *
     * @return \App\Service\LLM\ClaudeClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'LLM'.\DIRECTORY_SEPARATOR.'ClaudeClient.php';

        return $container->privates['App\\Service\\LLM\\ClaudeClient'] = new \App\Service\LLM\ClaudeClient(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('ANTHROPIC_API_KEY'), $container->getEnv('ANTHROPIC_MODEL'));
    }
}
