<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobOfferControllercreateJobOfferService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t9otC_a.App\Controller\JobOfferController::createJobOffer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t9otC_a.App\\Controller\\JobOfferController::createJobOffer()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dto' => ['privates', 'App\\Dto\\JobOffer\\CreateJobOfferDto', NULL, 'Cannot autowire service "App\\Dto\\JobOffer\\CreateJobOfferDto": argument "$title" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'dto' => 'App\\Dto\\JobOffer\\CreateJobOfferDto',
        ]))->withContext('App\\Controller\\JobOfferController::createJobOffer()', $container);
    }
}
