<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterUserDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\Auth\RegisterUserDto' shared autowired service.
     *
     * @return \App\Dto\Auth\RegisterUserDto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Dto\\Auth\\RegisterUserDto": argument "$email" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
