<?php

namespace ContainerQMGETvq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateJobOfferDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Dto\JobOffer\UpdateJobOfferDto' shared autowired service.
     *
     * @return \App\Dto\JobOffer\UpdateJobOfferDto
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Dto'.\DIRECTORY_SEPARATOR.'JobOffer'.\DIRECTORY_SEPARATOR.'UpdateJobOfferDto.php';

        return $container->privates['App\\Dto\\JobOffer\\UpdateJobOfferDto'] = new \App\Dto\JobOffer\UpdateJobOfferDto();
    }
}
